server:
  port: 80

spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: cyj7416146
      #url: jdbc:mysql://192.168.2.169:3306/docker_mysql01?useSSL=false
      url: jdbc:mysql://192.168.2.169:3306/docker_mysql01?useSSL=false
      max-active: 100
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'X'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20

#redis 配置
  redis:
    database: 0
    host: 192.168.2.169
    port: 6379
    password: cyj7416146
    timeout: 0
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1


#myabatis配置文件
mybatis:
  type-aliases-package: com.chenyj.mybatis.mapper
  mapper-locations: classpath:mapping/*.xml
  configuration:
    lazy-loading-enabled: true


logging:
      level:
        com.chenyj.mybatis.mapper: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

